import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: "#071018" },
  container: { flex: 1, paddingHorizontal: 20, paddingTop: 12 },
  brand: {
    fontSize: 28,
    fontWeight: "800",
    color: "#e8f1f7",
    letterSpacing: -0.6,
  },
  sub: { color: "#8fa6b6", marginTop: 4, marginBottom: 14 },
  composer: { flexDirection: "row", gap: 8 },
  input: {
    flex: 1,
    backgroundColor: "#050b11",
    borderColor: "rgba(148,183,204,0.16)",
    borderWidth: 1,
    borderRadius: 12,
    color: "#e8f1f7",
    paddingHorizontal: 14,
    paddingVertical: 12,
  },
  addBtn: {
    backgroundColor: "#5eead4",
    borderRadius: 12,
    paddingHorizontal: 16,
    justifyContent: "center",
  },
  addText: { color: "#04201c", fontWeight: "800" },
  row: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    paddingVertical: 10,
    borderBottomColor: "rgba(148,183,204,0.12)",
    borderBottomWidth: 1,
  },
  title: { flex: 1, color: "#e8f1f7", fontSize: 16 },
  done: { textDecorationLine: "line-through", color: "#8fa6b6" },
  secondary: {
    borderWidth: 1,
    borderColor: "rgba(148,183,204,0.16)",
    borderRadius: 10,
    paddingHorizontal: 10,
    paddingVertical: 8,
  },
  secondaryText: { color: "#e8f1f7", fontWeight: "600", fontSize: 12 },
  danger: {
    backgroundColor: "rgba(251,113,133,0.12)",
    borderRadius: 10,
    paddingHorizontal: 10,
    paddingVertical: 8,
  },
  dangerText: { color: "#fb7185", fontWeight: "700", fontSize: 12 },
  empty: { color: "#8fa6b6", marginTop: 12 },
  status: { color: "#8fa6b6", marginVertical: 12 },
  error: { color: "#fb7185" },
  label: {
    marginTop: 16,
    marginBottom: 6,
    color: "#5eead4",
    fontSize: 12,
    fontWeight: "700",
    letterSpacing: 0.6,
    textTransform: "uppercase",
  },
  stats: {
    color: "#c7d6e1",
    fontSize: 12,
    backgroundColor: "#050b11",
    borderRadius: 10,
    padding: 10,
    overflow: "hidden",
  },
  headerRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 8,
  },
  logoutBtn: {
    borderWidth: 1,
    borderColor: "rgba(148,183,204,0.16)",
    borderRadius: 10,
    paddingHorizontal: 10,
    paddingVertical: 8,
  },
  logoutText: { color: "#e8f1f7", fontWeight: "700", fontSize: 12 },
});
